tormod, -h, structure change wifi, add repair hotspot

diff --git a/command/hotspot b/command/hotspot
--- a/command/hotspot
+++ b/command/hotspot
@@ -3,7 +3,7 @@
 #copyright 2019; needs packages: nmap, hostapd, dnsmasq
 
 ap_ssid=$(cat /etc/hostapd/hostapd.conf | grep -Po '(?<=(?<!.)ssid=).*') #finds ssid in hostapd (positive lookahead with negative no char before)
-dhcp_ip='192.168.1.1'
+dhcp_ip='192.168.0.1'
 inet_ip='\b([0-9]{1,3}\.){3}[0-9]{1,3}\b'
 network_state=0
 ap_state=0
@@ -16,6 +16,7 @@ samba=0
 # Parameters are -open, -close, -auto, -h
 # samba 0 = internal share (AP)
 # samba 1 = external share
+
 
 connector() {
 	#$1 = interface
@@ -31,8 +32,9 @@ connector() {
 	ip a flush $1
 	ip a add $dhcp_ip/24 dev $1
 	systemctl start nmbd smbd
-	echo '--------> AP now running on first available interface:' $1
+	echo '--------> AP now running on interface:' $1
 }
+
 
 disconnector() {
 	#$1 = interface
@@ -45,54 +47,64 @@ disconnector() {
 	systemctl start dhcpcd@$1
 }
 
+
 repairer() {
 	#$1 = interface
-	if [[ ! $(systemctl status hostapd | grep 'Active: active (running') || ! $(iw dev | grep $ap_ssid) ]]; then
-		echo "hostapd not running -> restart"
-		systemctl restart hostapd
-		repair_state=1
-	fi
-	if ! [[ $(systemctl status dnsmasq | grep 'Active: active (running') ]]; then
-		echo "dnsmasq not running -> restart"
-		systemctl restart dnsmasq
-		repair_state=1
-	fi
-	if [[ $(systemctl status wpa_supplicant@$1 | grep 'Active: active (running') ]]; then
-		echo "wpa_supplicant@"$1 "running -> stopping"
-		systemctl stop wpa_supplicant@$1
-		repair_state=1
-	fi
-	if ! [[ $(ip a show $1 | grep $dhcp_ip) ]]; then
-		echo "AP has no static IP -> setting"
-		ip a add $dhcp_ip/24 dev $1
-		repair_state=1
-	fi
-	if ! [[ $(systemctl status nmbd | grep 'Active: active (running') ]]; then
-		echo "Samba Service nmbd not running -> restart"
-		systemctl restart nmbd
-		repair_state=1
-	fi
-	if ! [[ $(systemctl status smbd | grep 'Active: active (running') ]]; then
-		echo "Samba Service smbd not running -> restart"
-		systemctl restart smbd
-		repair_state=1
-	fi
-	if ! [[ $(ip link show $1 up) ]]; then
-		echo "Interface " $1 " is DOWN -> bringing UP"
-		ip link set $1 up
-	fi
-	if [[ $repair_state != 1 ]]; then
-		echo "--------> AP is working as expected"
+	if [[ -z $(iw dev | grep $ap_ssid) ]]; then
+		echo ''
+		echo '--------> no AP active, nothing to repair'
+		echo '--------> first open up AP, see help'
+		echo ''
 	else
-		echo "--------> AP repaired"
+		if [[ ! $(systemctl status hostapd | grep 'Active: active (running') || ! $(iw dev | grep $ap_ssid) ]]; then
+			echo "hostapd not running -> restart"
+			systemctl restart hostapd
+			repair_state=1
+		fi
+		if ! [[ $(systemctl status dnsmasq | grep 'Active: active (running') ]]; then
+			echo "dnsmasq not running -> restart"
+			systemctl restart dnsmasq
+			repair_state=1
+		fi
+		if [[ $(systemctl status wpa_supplicant@$1 | grep 'Active: active (running') ]]; then
+			echo "wpa_supplicant@"$1 "running -> stopping"
+			systemctl stop wpa_supplicant@$1
+			repair_state=1
+		fi
+		if ! [[ $(ip a show $1 | grep $dhcp_ip) ]]; then
+			echo "AP has no static IP -> setting"
+			ip a add $dhcp_ip/24 dev $1
+			repair_state=1
+		fi
+		if ! [[ $(systemctl status nmbd | grep 'Active: active (running') ]]; then
+			echo "Samba Service nmbd not running -> restart"
+			systemctl restart nmbd
+			repair_state=1
+		fi
+		if ! [[ $(systemctl status smbd | grep 'Active: active (running') ]]; then
+			echo "Samba Service smbd not running -> restart"
+			systemctl restart smbd
+			repair_state=1
+		fi
+		if ! [[ $(ip link show $1 up) ]]; then
+			echo "Interface " $1 " is DOWN -> bringing UP"
+			ip link set $1 up
+		fi
+		if [[ $repair_state != 1 ]]; then
+			echo "--------> AP is working as expected"
+		else
+			echo "--------> AP repaired"
+		fi
 	fi
 }
+
 
 forwarder() {
 	#$1 = take traffic incoming from interface $1
 	#$2 = forward traffic to interface $2
 	echo 'forwarding alle traffic from ' $1 ' to ' $2
 }
+
 
 devicer() {
 #create array with all external wifi interfaces and find first free device for connection
@@ -133,19 +145,29 @@ devicer() {
 				# 	connector ${wifi_devices[0]}
 				# fi
 		fi
-	elif [[ $1 == 'open' ]]; then	
-		for i in ${wifi_devices[@]} ; do
-			if [[ -z $(iw $i info | grep -o $ap_ssid) ]]; then
-				connector $i
-				repairer $i
-				break
+	#$3 is a user-specified interface
+	elif [[ $1 == 'open' ]]; then
+		if ! [[ -z $3 ]]; then
+			if [[ -z $(iw $3 info | grep -o $ap_ssid) ]]; then
+				connector $3
+				repairer $3
 			else
-				echo '--------> interface not available for hotspot:' $i
+				echo '--------> interface not available for hotspot:' $2
 			fi
-			if [[ -z $(iw dev | grep -o $ap_ssid) ]]; then
-				echo '--------> could not open AP!'
-			fi
-	        done
+		else
+			for i in ${wifi_devices[@]} ; do
+				if [[ -z $(iw $i info | grep -o $ap_ssid) ]]; then
+					connector $i
+					repairer $i
+					break
+				else
+					echo '--------> interface not available for hotspot:' $i
+				fi
+				if [[ -z $(iw dev | grep -o $ap_ssid) ]]; then
+					echo '--------> could not open AP!'
+				fi
+				done
+		fi
 	elif [[ $1 == 'close' ]]; then
 		for i in ${wifi_devices[@]} ; do
 			if [[ $(iw $i info | grep -o $ap_ssid) ]]; then
@@ -174,7 +196,7 @@ devicer() {
 ### Command Paramter	###
 ###						###
 
-if [[ $1 == '-auto' ]]; then
+if [[ $1 == '-a' || $1 == '--auto' ]]; then
 	#array with all default gateway-routes
 	n=0
 	for j in $(ip route | grep 'default' | grep -E -o $inet_ip)
@@ -234,46 +256,61 @@ esac
 ### Manual control Parameter	###
 ###								###
 
-elif [[ $1 == '-join' ]]; then
+elif [[ $1 == '-j' || $1 == '--join' ]]; then
 	echo ''
 	echo '------ Checking for known networks and rejoin... ------'
 	devicer join
 	echo ''
-elif [[ $1 == '-open' ]]; then
-        echo ""
-        echo "----- trying to open Access Point with samba -----"
-	devicer open
+elif [[ $1 == '-o' || $1 == '--open' ]]; then
+    echo ""
+    echo "----- trying to open Access Point with samba -----"
+	devicer open $2
 	echo "--------> done"
 	echo ""
-elif [[ $1 == '-close' ]]; then
+elif [[ $1 == '-c' || $1 == '--close' ]]; then
 	echo ""
-        echo "----- closing Access Point -----"
+    echo "----- closing Access Point -----"
 	devicer close
 	echo "--------> done"
-        echo ""
-elif [[ $1 == '-fordward' ]]; then
+    echo ""
+elif [[ $1 == '-r' || $1 == '--repair' ]]; then
+	echo ''
+	echo '----- checking repair of Access Point -----'
+	devicer repair
+	echo '--------> done'
+	echo ''	
+elif [[ $1 == '-f' || $1 == '--fordward' ]]; then
 	echo ''
 	echo 'Under construction...'
 	devicer forward $2 $3
 	echo ''
 	
-elif [[ $1 == '-h' ]]; then
+elif [[ $1 == '-h' || $1 == '--help' ]]; then
 	echo ''
-	echo '----- raspberry hotspot script v1.5 -----'
+	echo '----- raspberry hotspot script v1.6 -----'
 	echo 'This script was made for use as a cronjob. It will automatically open an AP if the PI does not have an active network connection. Set cronjob e.g. to every 5 minutes. Use parameter -auto for cron. You can use the other parameters to manually control the hotspot.'
+	echo 'Hotspot will ALWAYS KILL an active connection if necessary!'
 	echo ''
 	echo 'Usage:'
 	echo '[hotspot] [parameter] [opt1] [opt2]'
-    echo '[-auto]			auto Access-Point'
-	echo '[-join] 			checks for known networks and tries to reconnect'
-	echo '					Otherwise hotspot wont shut down and pi never connects to known networks automatically'
-	echo '[-open]			open Access-Point (thought for manual control)'
-	echo '[-close]			close Access-Point (thought for manual control)'
-	echo '[-fordward]		forward Access-Point to connected network'
-	echo '					or give [opt1 = from interface] [opt2 = to interface]'
+    echo '[-a] [--auto]       auto Access-Point'
+	echo ''
+	echo '[-j] [--join]       checks for known networks and tries to reconnect'
+	echo '                    Otherwise pi never connects to known networks automatically'
+	echo ''
+	echo '[-o] [--open]       open Access-Point (thought for manual control)'
+	echo '                    carefully: will force kill any connection on free interface!'
+	echo '                    [opt1 = interface for hotspot]'
+	echo ''
+	echo '[-c] [--close]      close Access-Point (thought for manual control)'
+	echo ''
+	echo '[-r] [--repair]     repair hotspot'
+	echo ''
+	echo '[-f] [--fordward]   forward Access-Point to connected network'
+	echo '                    or: [opt1 = from interface] [opt2 = to interface]'
 	echo ''
 else
 	echo ''
-	echo 'Type -h for help'
+	echo 'Type -h --help for help'
 	echo ''
 fi
diff --git a/command/wifi b/command/wifi
--- a/command/wifi
+++ b/command/wifi
@@ -2,22 +2,40 @@
 
 # This script will let you connect to existing APs by simple terminal-commands
 
+#todo: --known to list known networks
+# --reconnect: stop when a interface was able to reconnect
+# substract the AP-interface to prevent interruption through reconnect
+
+free_if=''					#stores the first found free interface
+
+
+#store all available wifi-interfaces in an array
+n=0
+for j in $(iw dev | grep -o 'wlan[0-99]') ; do
+	wifi_interfaces[$n]=$j
+	let "n= $n + 1"
+	if [ ! -f /etc/wpa_supplicant/wpa_supplicant-$j.conf ]; then
+		cp /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant-$j.conf
+	fi
+done
+
+
 #function for handling connection
 connector() {
 	#$1 = network
 	#$2 = passphrase
 	#$3 = device
-	ip link set $3 up
-	systemctl stop wpa_supplicant@$3.service
-	store_credentials "$1" "$2" "$3"
-	systemctl start wpa_supplicant@$3.service
+	ip link set $1 up
+	systemctl stop wpa_supplicant@$1.service
+	systemctl start wpa_supplicant@$1.service
 	#ip r del default
-	if ! [[ $(systemctl status dhcpcd@$3 | grep -o "active (running)") ]]; then
-		systemctl start dhcpcd@$3
+	if ! [[ $(systemctl status dhcpcd@$1 | grep -o "active (running)") ]]; then
+		systemctl start dhcpcd@$1
 	else
-		systemctl restart dhcpcd@$3
+		systemctl restart dhcpcd@$1
 	fi
 }
+
 
 disconnector() {
 	#$1 = device
@@ -35,44 +53,53 @@ disconnector() {
 	ip link set $1 down
 }
 
-device_checker() {
-	#$1 = device to check if its usable (type: managed AND without SSID)
-	if [[ -z $(iw $1 info | grep -o 'ssid') && $(iw $1 info | grep -o 'managed') ]]; then
-		return 0
+
+#$1 = device to check if its usable (type: managed AND without SSID)
+interface_checker() {
+	if [ -z "$1" ]; then
+		for i in ${wifi_interfaces[@]}
+		do
+			if [[ -z $(iw $i info | grep -o 'ssid') && $(iw $i info | grep -o 'managed') ]]; then
+				free_if=$i
+			else
+				free_if=''
+			fi
+		done
 	else
-		return 1
+		if [[ -z $(iw $1 info | grep -o 'ssid') && $(iw $1 info | grep -o 'managed') ]]; then
+			free_if=$1
+		else
+			free_if=''
+		fi
 	fi
 }
+
 
 store_credentials() {
 	#$1 = network
 	#$2 = passphrase
 	#$3 = device
-	if [ ! -f /etc/wpa_supplicant/wpa_supplicant-$3.conf ]; then
-		cp /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant-$3.conf
+	#stores the credentials in conf for every interface
+	for i in ${wifi_interfaces[@]}
+	do
+	if [ ! -f /etc/wpa_supplicant/wpa_supplicant-$i.conf ]; then
+		cp /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant-$i.conf
 	fi	
-	( echo "" ; wpa_passphrase "$1" "$2" ) >> /etc/wpa_supplicant/wpa_supplicant-$3.conf
+	( echo "" ; wpa_passphrase "$1" "$2" ) >> /etc/wpa_supplicant/wpa_supplicant-$i.conf
+	done
 	echo 'Network and credentials stored.'
 }
 
-#store all wifi-interfaces in an array
-n=0
-for j in $(iw dev | grep -o 'wlan[0-99]') ; do
-	wifi_devices[$n]=$j
-	let "n= $n + 1"
-	if [ ! -f /etc/wpa_supplicant/wpa_supplicant-$j.conf ]; then
-		cp /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant-$j.conf
-	fi
-done
 
 ###						###
 ### Settings start here ###
 ###						###
-			
-if [[ $1 == '-device' ]]; then
+
+
+if [[ $1 == '-i' || $1 == '--interface' ]]; then
 	echo ''
 	echo 'Available devices and state:'
-	for i in ${wifi_devices[@]}
+	for i in ${wifi_interfaces[@]}
 	do
 		#check connected devices and their network
 		if [[ $(iw $i info | grep -o 'ssid') ]]; then
@@ -85,27 +112,80 @@ if [[ $1 == '-device' ]]; then
 	done
 	echo ''
 
-elif [[ $1 == '-scan' ]]; then
+#$2 specified interface or use any available (doesn't have to be free)
+elif [[ $1 == '-s' || $1 == '--scan' ]]; then
 	if  [[ -n $2 ]]; then
 		echo 'Using' $2 'for scan...'
 		ip link set $2 up
 		iw dev $2 scan | grep 'SSID:'
 		echo ''
 	else
-		#for i in ${wifi_devices[@]}
-		if [ "${#wifi_devices[@]}" == 0 ]; then
+		if [ "${#wifi_interfaces[@]}" == 0 ]; then
 			echo ''
-			echo 'No wifi-interfaces were found! Scan not possible. Check interfaces "iw dev" ?'
+			echo 'There is no interface available.'
+			echo 'Scan not possible.'
 			echo ''
 		else
 			echo ''
-			echo  'First available interface:' ${wifi_devices[0]} '- found networks:'
-			ip link set ${wifi_devices[0]} up 
-			iw dev ${wifi_devices[0]} scan | grep 'SSID:'
+			echo 'Found available interface:' ${wifi_interfaces[0]}			
+			echo 'Networks in range:'
+			ip link set ${wifi_interfaces[0]} up 
+			iw dev ${wifi_interfaces[0]} scan | grep 'SSID:'
 			echo ''
 		fi
 	fi
-elif [[ $1 == '-connect' ]]; then
+elif [[ $1 == '-r' || $1 == '--reconnect' ]]; then
+		echo ''
+		echo 'Trying to reconnect existing network...'
+		echo ''
+	if [ -z $2 ]; then
+		for i in ${wifi_interfaces[@]} 
+		do
+			interface_checker $i
+			if ! [ "$free_if" == '' ]; then
+				echo ''
+				echo 'Using' $free_if 'for reconnection...'
+				echo 'Waiting for network...'
+				echo ''
+				connector $free_if
+				break
+			fi
+		done
+		
+	else
+		interface_checker $2
+		if [ "$free_if" == "$2" ]; then				
+			echo ''
+			echo 'Using' $2 'for reconnection...'
+			echo 'Waiting for network...'
+			echo ''
+			connector $2
+		fi
+	fi
+	if [ "$free_if" == '' ]; then
+		echo ''
+		echo 'There is no free interface available.'
+		echo 'Connection not possible.'
+		echo ''			
+	elif ! [ "$free_if" == '' ]; then
+		for i in {1..10} 
+			do
+			if [[ $(iw $free_if dev | grep -o 'ssid') ]]; then
+				echo ''
+				echo 'Connection established.'
+				echo ''
+				break
+			elif [ i == '10' ]; then
+				echo ''
+				echo 'Reconnection not possible.'
+				echo 'Unknown problem. New passphrase?'
+				echo ''
+			fi
+			sleep 1s
+		done
+	fi
+
+elif [[ $1 == '-c' || $1 == '--connect' ]]; then
 # $2 = network to connect
 # $3 = passphrase
 # $4 = device
@@ -120,51 +200,49 @@ elif [[ $1 == '-connect' ]]; then
 		echo ''
 		#did user specify an interface?
 		if  [[ -z $4 ]]; then
-			for i in ${wifi_devices[@]}
-				do
-				n=0
-				#check if any interface is without ssid but managed (so usable)
-				if device_checker $i == "0" ; then
-					echo  'First free:' $i '- using for connection...'
-					connector "$2" "$3" "$i"
-					n=1
-					break
-				else
-					store_credentials "$2" "$3" "$i"
-					echo 'Device not available for connection: ' $i
-					echo 'Check interfaces and try again. Maybe hotspot active?'
-				fi
-			done
-			if (( $n >= "1" )) ; then
+			interface_checker
+			if [ "$free_if" == '' ]; then
+				echo ''
+				echo 'There is no free interface available.'
+				echo 'Connection not possible.'
+				echo ''			
+			else
+				echo ''
+				echo 'Found available interface:' $free_if
+				store_credentials "$2" "$3" "$free_if"
+				connector "$free_if"
 				echo ''
 				echo 'Connection established.'
 				echo ''
-			elif (( $n == "0" )) ; then
-				echo ''
-				echo 'There is no free interface available. Check with -device.'
-				echo ''
 			fi
 		else
-			#check if specified interface is free
-			if device_checker $4 == "0"  ; then
-				connector "$2" "$3" "$4" 
-			else	
+			#check if specified interface is in the free-array
+			interface_checker $4
+			if [ "$free_if" == '' ]; then
 				echo ''
-				echo 'Interface' $4 'is busy. Aborting... Please check.'
+				echo 'Interface' $4 'not available. Aborting...'
+				echo 'Check free interfaces and try again.'
 				echo ''
-			fi
+			else
+				store_credentials "$2" "$3" "$4"
+				connector "$4"
+				echo ''
+				echo 'Using' $2 'for connection...'
+				echo 'Connection established.'
+				echo ''
+			fi	
 		fi
 	fi
-elif [[ $1 == '-disconnect' ]]; then
+elif [[ $1 == '-d' || $1 == '--disconnect' ]]; then
 #2 = device to disconnect
 	if [[ -z $2 ]]; then
 		echo 'Please specifiy interface to be disconnected! Aborting...'
 	else 
 		disconnector $2
 	fi
-elif [[ $1 == '-known' ]]; then
-        if [[ $2 == '-remove' ]]; then
-                if [[ $3 == '-all' ]]; then
+elif [[ $1 == '-k' || $1 == '--known' ]]; then
+        if [[ $2 == '-r' || $2 == '--remove' ]]; then
+                if [[ $3 == '-a' || $3 == '--all' ]]; then
                         echo ''
                         echo 'Removing all known networks from /etc/wpa_supplicant/ ...'
 						echo ''
@@ -180,25 +258,34 @@ elif [[ $1 == '-known' ]]; then
                 echo ''
                 echo 'List of known wifi-networks:'
         fi
-elif [[ $1 == '-h' ]]; then
-echo ''
-echo '----- simple wifi scan & connect script v1.5 -----'
-echo ''
-echo 'Usage:'
-echo 'wifi [option] [device]'
-echo '[-device]	List all devices and state (free or AP).'
-echo '[-scan]       Scans for networks.'
-echo '[-connect]    Connect to network with param [network] [passphrase] [device]'
-echo '[-disconnect] Disconnect a device from network'
-echo '[-known]      List known wifi-networks and remove specified or all'
-echo '              [-remove] [ssid] or [-all]'
-echo ''
-echo 'ATTENTION: If any whitespaces in network or passphrase use " "!'
-echo ''
-echo 'If no device is given the first available will be used.'
-echo ''
+elif [[ $1 == '-h' || $1 == '--help' ]]; then
+	echo ''
+	echo '----- simple wifi scan & connect script v1.6 -----'
+	echo ''
+	echo 'Usage:'
+	echo '[wifi] [parameter] [opt1]'
+	echo ''
+	echo '[parameter]:'
+	echo '[-i] [--interface]	  List all devices and state (free or AP).'
+	echo ''
+	echo '[-s] [--scan]           Scans for networks with first free interface'
+	echo '                        [opt1]: optional specify used interface'
+	echo ''
+	echo '[-c] [--connect]        Connect to network with param [network] [passphrase] [device]'
+	echo ''
+	echo '[-r] [--reconnect]      Automatically try a reconnect to any known network in range.'
+	echo ''
+	echo '[-d] [--disconnect]     Disconnect a device from network'
+	echo ''
+	echo '[-k] [--known]          List known wifi-networks and remove specified or all'
+	echo '                        [-r][--remove] [ssid] or [-a][--all]'
+	echo ''
+	echo 'ATTENTION: If any whitespaces in network or passphrase use " "!'
+	echo ''
+	echo 'If no device is given the first available will be used.'
+	echo ''
 else
-echo ''
-echo 'use -h for help!'
-echo ''
+	echo ''
+	echo 'Type -h --help for help'
+	echo ''
 fi
